
version: 2

models:
  - name: src
    description: "source generated data"
    columns:
      - name: txt
        description: "generated data"

  - name: inject_raw
    description: "source included data"
    columns:
      - name: first_name
        description: "included first_name"

